version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
  dbinit:
    build:
      context: ./initdb
      dockerfile: Dockerfile    
    depends_on:
      - "db"
    environment:
      - adminURL=postgresql://postgres:pass@db/postgres
      - dbURL=postgresql://postgres:pass@db/shipping
      - dbName=shipping
  portdomainservice:
    build:
      context: ./service
      dockerfile: Dockerfile
    depends_on:
      - "dbinit"
    environment:
      - psqlURL=postgresql://postgres:pass@db/shipping
      - grpcPort=5000
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - "portdomainservice"
    environment:
      - portDomainServiceAddress=portdomainservice:5000