version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
  portdomainservice:
    build:
      context: ./service
      dockerfile: Dockerfile
    environment:
      - psqlURL=postgresql://postgres:pass@db/shipping?sslmode=require
      - grpcPort=5000
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - portDomainServiceAddress=portdomainservice:5000